apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: votoznotna-com-tls
spec:
  secretName: votoznotna-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: votoznotna.com
  dnsNames:
    - votoznotna.com
    - www.votoznotna.com
